/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package husacct.validate.presentation;

/**
 *
 * @author Jorik
 */
public class LanguageSeverityConfiguration extends javax.swing.JPanel {

    /** Creates new form LanguageSeverityConfiguration */
    public LanguageSeverityConfiguration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        ruletypeSeverity = new javax.swing.JPanel();
        rtsCategoryScrollpane = new javax.swing.JScrollPane();
        rtsCategory = new javax.swing.JList();
        rtsRuletypeScrollpane = new javax.swing.JScrollPane();
        rtsRuletypeTable = new javax.swing.JTable();
        rtsApply = new javax.swing.JButton();
        rtsRestore = new javax.swing.JButton();
        rtsRestoreAll = new javax.swing.JButton();
        violationtypeSeverity = new javax.swing.JPanel();
        vtsCategoryScrollpane = new javax.swing.JScrollPane();
        vtsCategory = new javax.swing.JList();
        vtsViolationtypeScrollpane = new javax.swing.JScrollPane();
        vtsViolationtypeTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        rtsCategory.setBorder(javax.swing.BorderFactory.createTitledBorder("Category"));
        rtsCategory.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        rtsCategoryScrollpane.setViewportView(rtsCategory);

        rtsRuletypeTable.setModel(ruletypeModel);
        rtsRuletypeTable.setFillsViewportHeight(true);
        rtsRuletypeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rtsRuletypeScrollpane.setViewportView(rtsRuletypeTable);

        rtsApply.setText("Apply");

        rtsRestore.setText("<html>Restore<br> to default");
        rtsRestore.setActionCommand("Restore to default");
        rtsRestore.setEnabled(false);

        rtsRestoreAll.setText("<html>Restore all<br> to default");

        javax.swing.GroupLayout ruletypeSeverityLayout = new javax.swing.GroupLayout(ruletypeSeverity);
        ruletypeSeverity.setLayout(ruletypeSeverityLayout);
        ruletypeSeverityLayout.setHorizontalGroup(
            ruletypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ruletypeSeverityLayout.createSequentialGroup()
                .addComponent(rtsCategoryScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtsRuletypeScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ruletypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ruletypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rtsRestore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rtsRestoreAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rtsApply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ruletypeSeverityLayout.setVerticalGroup(
            ruletypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rtsCategoryScrollpane)
            .addComponent(rtsRuletypeScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ruletypeSeverityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtsRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtsRestoreAll, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtsApply)
                .addContainerGap())
        );

        tabbedPane.addTab("Set ruletype severity", ruletypeSeverity);

        vtsCategory.setBorder(javax.swing.BorderFactory.createTitledBorder("Category"));
        vtsCategory.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        vtsCategoryScrollpane.setViewportView(vtsCategory);

        vtsViolationtypeTable.setModel(ruletypeModel);
        vtsViolationtypeTable.setFillsViewportHeight(true);
        vtsViolationtypeScrollpane.setViewportView(vtsViolationtypeTable);

        jButton4.setText("<html>Restore<br> to default");
        jButton4.setActionCommand("Restore to default");
        jButton4.setEnabled(false);

        jButton5.setText("<html>Restore all<br> to default");

        jButton6.setText("Apply");

        javax.swing.GroupLayout violationtypeSeverityLayout = new javax.swing.GroupLayout(violationtypeSeverity);
        violationtypeSeverity.setLayout(violationtypeSeverityLayout);
        violationtypeSeverityLayout.setHorizontalGroup(
            violationtypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(violationtypeSeverityLayout.createSequentialGroup()
                .addComponent(vtsCategoryScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vtsViolationtypeScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(violationtypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(violationtypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        violationtypeSeverityLayout.setVerticalGroup(
            violationtypeSeverityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vtsCategoryScrollpane)
            .addComponent(vtsViolationtypeScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, violationtypeSeverityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        tabbedPane.addTab("Set violation severity", violationtypeSeverity);

        jList3.setBorder(javax.swing.BorderFactory.createTitledBorder("Category"));
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList3);

        jTable3.setModel(ruletypeModel);
        jTable3.setFillsViewportHeight(true);
        jScrollPane6.setViewportView(jTable3);

        jList4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruletypes"));
        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList4);

        jButton7.setText("Select all");
        jButton7.setActionCommand("Restore to default");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Deselect all");

        jButton9.setText("Apply");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        tabbedPane.addTab("Set violationtype active per ruletype severit", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane))
        );

        tabbedPane.getAccessibleContext().setAccessibleName("Set ruletype severity");
    }// </editor-fold>//GEN-END:initComponents

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton rtsApply;
    private javax.swing.JList rtsCategory;
    private javax.swing.JScrollPane rtsCategoryScrollpane;
    private javax.swing.JButton rtsRestore;
    private javax.swing.JButton rtsRestoreAll;
    private javax.swing.JScrollPane rtsRuletypeScrollpane;
    private javax.swing.JTable rtsRuletypeTable;
    private javax.swing.JPanel ruletypeSeverity;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel violationtypeSeverity;
    private javax.swing.JList vtsCategory;
    private javax.swing.JScrollPane vtsCategoryScrollpane;
    private javax.swing.JScrollPane vtsViolationtypeScrollpane;
    private javax.swing.JTable vtsViolationtypeTable;
    // End of variables declaration//GEN-END:variables
}
